[{assign var="isAssetsNecessary" value=false}]
[{foreach from=$oView->getPaymentList() item=paymentObj name=paymentListCheck}]
    [{if $paymentObj->showInPaymentCtrl()}]
        [{assign var="isAssetsNecessary" value=true}]
    [{/if}]
[{/foreach}]
[{if $oView->isValidAdyenAuthorisation()}]
    [{assign var="isAssetsNecessary" value=false}]
[{/if}]
[{if $oViewConf|method_exists:'checkAdyenHealth' && $oViewConf->checkAdyenHealth() && $isAssetsNecessary}]
    [{* We include it as template, so that it can be modified in custom themes *}]
    [{include file="modules/osc/adyen/payment/adyen_assets.tpl"}]
[{/if}]
[{$smarty.block.parent}]