[{if $oViewConf|method_exists:'checkAdyenHealth' && $oViewConf->checkAdyenHealth() && $payment->getId() == $oViewConf->getAdyenPaymentPayPalId()}]
    [{* We include it as template, so that it can be modified in custom themes *}]
    [{include file="modules/osc/adyen/payment/adyen_assets.tpl"}]
    [{include file="modules/osc/adyen/payment/adyen_order_submit.tpl"}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]
